IF OBJECT_ID('[DESCONOCIDOS4].FN_OBTENER_CANTIDAD_INTENTOS_FALLIDOS_DE_INGRESO','FN') IS NOT NULL
	DROP FUNCTION [DESCONOCIDOS4].FN_OBTENER_CANTIDAD_INTENTOS_FALLIDOS_DE_INGRESO;
GO

CREATE FUNCTION [DESCONOCIDOS4].FN_OBTENER_CANTIDAD_INTENTOS_FALLIDOS_DE_INGRESO(@Usu_Id INT)
RETURNS INT
AS
BEGIN
RETURN (SELECT Usu_cantIntentosLoginFallidos FROM [DESCONOCIDOS4].USUARIO WHERE Usu_Id=@Usu_Id)
END
GO
