USE [pubs]
IF NOT EXISTS (
SELECT schema_name
FROM information_schema.SCHEMATA
WHERE schema_name = 'DESCONOCIDOS4' )
BEGIN
EXEC sp_executesql N'CREATE SCHEMA DESCONOCIDOS4'
END
GO

/*---------Limpieza de Tablas-------------*/
IF OBJECT_ID('DESCONOCIDOS4.TURNO') IS NOT NULL
DROP TABLE DESCONOCIDOS4.TURNO ;

GO
IF OBJECT_ID('DESCONOCIDOS4.CLIENTE') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.CLIENTE ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.VIAJE') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.VIAJE ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.AUTO') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.AUTO ;
END;

GO
IF OBJECT_ID('DESCONOCIDOS4.TIPO_AUTO') IS NOT NULL
BEGIN
DROP TABLE GOODFELLAS.TIPO_AUTO ;
END;
GO
IF OBJECT_ID('GOODFELLAS.CHOFER') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.CHOFER ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.CABECERO_FACTURA') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.CABECERO_FACTURA ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.RENDICION') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.RENDICION ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.ITEM_FACTURA') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.ITEM_FACTURA ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.USUARIO') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.USUARIO ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.USUARIO_ROL') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.USUARIO_ROL ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.ROL') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.ROL ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.FUNCIONALIDADXROL') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.FUNCIONALIDADXROL ;
END;
GO
IF OBJECT_ID('DESCONOCIDOS4.FUNCIONALIDAD') IS NOT NULL
BEGIN
DROP TABLE DESCONOCIDOS4.FUNCIONALIDAD ;
END;
GO

/*---------Definiciones de Tabla-------------*/

CREATE TABLE [DESCONOCIDOS4].TURNO(
Turno_Id INT NOT NULL IDENTITY(1,1), 
Turno_Hora_Inicio NUMERIC(18,0),
Turno_Hora_Fin NUMERIC(18,0),
Turno_Descripcion VARCHAR(255),
Turno_Valor_Kilometro NUMERIC(18,2),
Turno_Precio_Base NUMERIC(18,2),
PRIMARY KEY(Turno_Id));
GO
CREATE TABLE [DESCONOCIDOS4].CLIENTE(
Cliente_Id INT,
Cliente_Per_Id INT ,
Cliente_Dni NUMERIC(18,0),
Cliente_Nombre VARCHAR(255),
Cliente_Apellido VARCHAR(255),
Cliente_Direccion VARCHAR(255),
Cliente_Telefono NUMERIC(18,0),
Cliente_Mail VARCHAR(255),
Cliente_Fecha_Nac DATETIME,
Cliente_Habilitado BIT DEFAULT 1,
);
GO
CREATE TABLE [DESCONOCIDOS4].VIAJE(
Viaje_Nro INT,
Viaje_Chofer INT,
Viaje_Cliente INT,
Viaje_Cantidad_Km NUMERIC(18,0),
Viaje_Fecha_Hora_Inicio DATETIME,
Viaje_Fecha_Hora_Fin DATETIME,
Viaje_Turno INT,
);
GO
CREATE TABLE [DESCONOCIDOS4].AUTO(
Auto_Patente VARCHAR(10) NOT NULL,
Auto_Chofer INT,
Auto_Turno INT,
Auto_Codigo INT NOT NULL,
Auto_Licencia VARCHAR(26),
Auto_Habilitado BIT DEFAULT 1,
);

GO
CREATE TABLE [DESCONOCIDOS4].TIPO_AUTO(
Auto_Codigo INT NOT NULL,
Auto_Modelo VARCHAR(255),
Auto_Marca VARCHAR(255),
Auto_Rodado VARCHAR(10),
PRIMARY KEY(Auto_Codigo));
GO
CREATE TABLE [DESCONOCIDOS4].CHOFER(
Chofer_Id INT NOT NULL,
Chofer_Per_Id INT NOT NULL,
Chofer_Dni NUMERIC(18,0),
Chofer_Nombre VARCHAR(255),
Chofer_Apellido VARCHAR(255),
Chofer_Direccion VARCHAR(255),
Chofer_Telefono_1 NUMERIC(18,0),
Chofer_Mail VARCHAR(50),
Chofer_Fecha_Nac DATETIME,
Chofer_Telefono_2 DATETIME,
Chofer_Habilitado BIT DEFAULT 1,
);
GO
CREATE TABLE [DESCONOCIDOS4].CABECERO_FACTURA(
Cab_Fac_Nro NUMERIC(18,0),
Cab_Fac_Fecha DATETIME,
Cab_Fac_Cliente INT,
Cab_Fac_Fecha_Inicio DATETIME,
Cab_Fac_Fecha_Fin DATETIME,
Cab_Fac_Total_Fac NUMERIC(18,2),
);
GO
CREATE TABLE [DESCONOCIDOS4].RENDICION(
Rendicion_Nro NUMERIC(18,0),
Rendicion_Fecha DATETIME,
Rendicion_Chofer INT,
Rendicion_Importe NUMERIC(18,2),
Rendicion_Turno INT
);
GO
CREATE TABLE [DESCONOCIDOS4].ITEM_FACTURA(
Item_Fac_Nro_Fac INT NOT NULL IDENTITY(1,10),
Item_Fac_Cliente INT,
Item_Fac_Fecha DATETIME,
Item_Fac_Item INT,
Item_Fac_Fecha_Hora_Inicio DATETIME,
Item_Fac_Fecha_Hora_Fin DATETIME,
Item_Fac_Cant_Km NUMERIC(18,0),
Item_Fac_Precio_Base NUMERIC(18,2),
Item_Fac_Valor_Km INT,
Item_Fac_Total_Viaje NUMERIC(18,2),
);
GO
CREATE TABLE [DESCONOCIDOS4].USUARIO(
Usu_Per_Id INT IDENTITY(1,1),
Usu_Nombre VARCHAR (255),
Usu_Password VARCHAR(20),
Usu_Habilitado BIT DEFAULT 1,
Usu_Cant_Log_Fallidos SMALLINT,
);
GO
CREATE TABLE [DESCONOCIDOS4].USUARIO_ROL(
UsuRol_Usu_Id INT IDENTITY(1,1),
UsuRol_Rol_Id INT,
);
GO
CREATE TABLE [DESCONOCIDOS4].ROL(
Rol_Id INT IDENTITY(1,1),
Rol_Nombre VARCHAR(255),
Rol_Habilitado BIT DEFAULT 1,
);
GO
CREATE TABLE [DESCONOCIDOS4].FUNCIONALIDADXROL(
FuncRol_Rol_Id INT IDENTITY(1,1),
FunRol_Func_Id INT,
);
GO
CREATE TABLE [DESCONOCIDOS4].FUNCIONALIDAD(
Func_Id INT IDENTITY(1,1),
Func_Nombre VARCHAR(255),
Func_Descripcion VARCHAR(255),
);
GO